version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: musestruct_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-musestruct}
      POSTGRES_USER: ${POSTGRES_USER:-musestruct}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-musestruct123}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-musestruct} -d ${POSTGRES_DB:-musestruct}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
