version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: musestruct_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-musestruct}
      POSTGRES_USER: ${POSTGRES_USER:-musestruct}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-musestruct123}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-musestruct} -d ${POSTGRES_DB:-musestruct}"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: musestruct_backend
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-musestruct}:${POSTGRES_PASSWORD:-musestruct123}@postgres:5432/${POSTGRES_DB:-musestruct}
      RUST_LOG: ${RUST_LOG:-info}
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    volumes:
      - backend_cache:/app/cache
      - ./backend/own_music:/app/own_music
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  backend_cache:
    driver: local
