pub mod user;
pub mod album;
pub mod canonical_album;
pub mod canonical_album_track;
pub mod canonical_playlist;
pub mod canonical_playlist_track;
pub mod canonical_track;
pub mod qobuz_album;
pub mod qobuz_album_track;
pub mod qobuz_playlist;
pub mod qobuz_playlist_track;
pub mod qobuz_track;
pub mod server_album;
pub mod server_album_track;
pub mod server_playlist;
pub mod server_playlist_track;
pub mod server_track;
pub mod song;
pub mod spotify_album;
pub mod spotify_album_track;
pub mod spotify_playlist;
pub mod spotify_playlist_track;
pub mod spotify_track;
pub mod playlist;
pub mod playlist_item;
pub mod playlist_song;
pub mod streaming_service;
pub mod tidal_album;
pub mod tidal_album_track;
pub mod tidal_playlist;
pub mod tidal_playlist_track;
pub mod tidal_track;
pub mod user_playlist;
pub mod user_playlist_item;
pub mod user_queue_item;
pub mod user_session;
pub mod user_track;
pub mod favourite_track;
pub mod saved_track;
pub mod saved_album;
pub mod queue_item;

// Re-export specific entities to avoid namespace conflicts
pub use user::{Entity as UserEntity, Model as UserModel, ActiveModel as UserActiveModel, Column as UserColumn};
pub use album::{Entity as AlbumEntity, Model as AlbumModel, ActiveModel as AlbumActiveModel, Column as AlbumColumn};
pub use canonical_album::{Entity as CanonicalAlbumEntity, Model as CanonicalAlbumModel, ActiveModel as CanonicalAlbumActiveModel, Column as CanonicalAlbumColumn};
pub use canonical_album_track::{Entity as CanonicalAlbumTrackEntity, Model as CanonicalAlbumTrackModel, ActiveModel as CanonicalAlbumTrackActiveModel, Column as CanonicalAlbumTrackColumn};
pub use canonical_playlist::{Entity as CanonicalPlaylistEntity, Model as CanonicalPlaylistModel, ActiveModel as CanonicalPlaylistActiveModel, Column as CanonicalPlaylistColumn};
pub use canonical_playlist_track::{Entity as CanonicalPlaylistTrackEntity, Model as CanonicalPlaylistTrackModel, ActiveModel as CanonicalPlaylistTrackActiveModel, Column as CanonicalPlaylistTrackColumn};
pub use canonical_track::{Entity as CanonicalTrackEntity, Model as CanonicalTrackModel, ActiveModel as CanonicalTrackActiveModel, Column as CanonicalTrackColumn};
pub use qobuz_album::{Entity as QobuzAlbumEntity, Model as QobuzAlbumModel, ActiveModel as QobuzAlbumActiveModel, Column as QobuzAlbumColumn};
pub use qobuz_album_track::{Entity as QobuzAlbumTrackEntity, Model as QobuzAlbumTrackModel, ActiveModel as QobuzAlbumTrackActiveModel, Column as QobuzAlbumTrackColumn};
pub use qobuz_playlist::{Entity as QobuzPlaylistEntity, Model as QobuzPlaylistModel, ActiveModel as QobuzPlaylistActiveModel, Column as QobuzPlaylistColumn};
pub use qobuz_playlist_track::{Entity as QobuzPlaylistTrackEntity, Model as QobuzPlaylistTrackModel, ActiveModel as QobuzPlaylistTrackActiveModel, Column as QobuzPlaylistTrackColumn};
pub use qobuz_track::{Entity as QobuzTrackEntity, Model as QobuzTrackModel, ActiveModel as QobuzTrackActiveModel, Column as QobuzTrackColumn};
pub use server_album::{Entity as ServerAlbumEntity, Model as ServerAlbumModel, ActiveModel as ServerAlbumActiveModel, Column as ServerAlbumColumn};
pub use server_album_track::{Entity as ServerAlbumTrackEntity, Model as ServerAlbumTrackModel, ActiveModel as ServerAlbumTrackActiveModel, Column as ServerAlbumTrackColumn};
pub use server_playlist::{Entity as ServerPlaylistEntity, Model as ServerPlaylistModel, ActiveModel as ServerPlaylistActiveModel, Column as ServerPlaylistColumn};
pub use server_playlist_track::{Entity as ServerPlaylistTrackEntity, Model as ServerPlaylistTrackModel, ActiveModel as ServerPlaylistTrackActiveModel, Column as ServerPlaylistTrackColumn};
pub use server_track::{Entity as ServerTrackEntity, Model as ServerTrackModel, ActiveModel as ServerTrackActiveModel, Column as ServerTrackColumn};
pub use song::{Entity as SongEntity, Model as SongModel, ActiveModel as SongActiveModel, Column as SongColumn};
pub use spotify_album::{Entity as SpotifyAlbumEntity, Model as SpotifyAlbumModel, ActiveModel as SpotifyAlbumActiveModel, Column as SpotifyAlbumColumn};
pub use spotify_album_track::{Entity as SpotifyAlbumTrackEntity, Model as SpotifyAlbumTrackModel, ActiveModel as SpotifyAlbumTrackActiveModel, Column as SpotifyAlbumTrackColumn};
pub use spotify_playlist::{Entity as SpotifyPlaylistEntity, Model as SpotifyPlaylistModel, ActiveModel as SpotifyPlaylistActiveModel, Column as SpotifyPlaylistColumn};
pub use spotify_playlist_track::{Entity as SpotifyPlaylistTrackEntity, Model as SpotifyPlaylistTrackModel, ActiveModel as SpotifyPlaylistTrackActiveModel, Column as SpotifyPlaylistTrackColumn};
pub use spotify_track::{Entity as SpotifyTrackEntity, Model as SpotifyTrackModel, ActiveModel as SpotifyTrackActiveModel, Column as SpotifyTrackColumn};
pub use playlist::{Entity as PlaylistEntity, Model as PlaylistModel, ActiveModel as PlaylistActiveModel, Column as PlaylistColumn};
pub use playlist_item::{Entity as PlaylistItemEntity, Model as PlaylistItemModel, ActiveModel as PlaylistItemActiveModel, Column as PlaylistItemColumn};
pub use playlist_song::{Entity as PlaylistSongEntity, Model as PlaylistSongModel, ActiveModel as PlaylistSongActiveModel, Column as PlaylistSongColumn};
pub use streaming_service::{Entity as StreamingServiceEntity, Model as StreamingServiceModel, ActiveModel as StreamingServiceActiveModel, Column as StreamingServiceColumn};
pub use tidal_album::{Entity as TidalAlbumEntity, Model as TidalAlbumModel, ActiveModel as TidalAlbumActiveModel, Column as TidalAlbumColumn};
pub use tidal_album_track::{Entity as TidalAlbumTrackEntity, Model as TidalAlbumTrackModel, ActiveModel as TidalAlbumTrackActiveModel, Column as TidalAlbumTrackColumn};
pub use tidal_playlist::{Entity as TidalPlaylistEntity, Model as TidalPlaylistModel, ActiveModel as TidalPlaylistActiveModel, Column as TidalPlaylistColumn};
pub use tidal_playlist_track::{Entity as TidalPlaylistTrackEntity, Model as TidalPlaylistTrackModel, ActiveModel as TidalPlaylistTrackActiveModel, Column as TidalPlaylistTrackColumn};
pub use tidal_track::{Entity as TidalTrackEntity, Model as TidalTrackModel, ActiveModel as TidalTrackActiveModel, Column as TidalTrackColumn};
pub use user_playlist::{Entity as UserPlaylistEntity, Model as UserPlaylistModel, ActiveModel as UserPlaylistActiveModel, Column as UserPlaylistColumn};
pub use user_playlist_item::{Entity as UserPlaylistItemEntity, Model as UserPlaylistItemModel, ActiveModel as UserPlaylistItemActiveModel, Column as UserPlaylistItemColumn};
pub use user_queue_item::{Entity as UserQueueItemEntity, Model as UserQueueItemModel, ActiveModel as UserQueueItemActiveModel, Column as UserQueueItemColumn};
pub use user_session::{Entity as UserSessionEntity, Model as UserSessionModel, ActiveModel as UserSessionActiveModel, Column as UserSessionColumn};
pub use user_track::{Entity as UserTrackEntity, Model as UserTrackModel, ActiveModel as UserTrackActiveModel, Column as UserTrackColumn};
pub use favourite_track::{Entity as FavouriteTrackEntity, Model as FavouriteTrackModel, ActiveModel as FavouriteTrackActiveModel, Column as FavouriteTrackColumn};
pub use saved_track::{Entity as SavedTrackEntity, Model as SavedTrackModel, ActiveModel as SavedTrackActiveModel, Column as SavedTrackColumn};
pub use saved_album::{Entity as SavedAlbumEntity, Model as SavedAlbumModel, ActiveModel as SavedAlbumActiveModel, Column as SavedAlbumColumn};
pub use queue_item::{Entity as QueueItemEntity, Model as QueueItemModel, ActiveModel as QueueItemActiveModel, Column as QueueItemColumn};

// Re-export DTOs without prefix
pub use user::{CreateUserDto, LoginDto, UserResponseDto};
pub use album::AlbumResponseDto;
pub use song::{SongResponseDto, SearchQuery};
pub use playlist::{PlaylistResponseDto, CreatePlaylistDto, UpdatePlaylistDto};
pub use playlist_item::{PlaylistItemResponseDto, AddPlaylistItemDto, ReorderPlaylistItemDto};
pub use playlist_song::{PlaylistSongResponseDto, AddSongToPlaylistDto};
pub use streaming_service::{StreamingServiceResponseDto, ConnectServiceDto};
pub use queue_item::{QueueItemResponseDto, AddToQueueDto, ReorderQueueDto};
